on:
    [ push ]

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install
      - run: yarn lint
      - run: yarn build
