on:
    [ push ]

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: cd packages/chatbot-backend
      - run: yarn install
      - run: yarn lint
      - run: yarn build
